---
# tasks file for roles/haproxy# Closing and disabling firewalld
- name: "Closing firewalld"
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: "upgrade all packages"
  yum: name=* state=latest

- name: "Install haproxy"
  yum: 
    name: haproxy
    state: present

- name: "Configure haproxy"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: "Let haproxey connect anywhere"
  shell: setsebool -P haproxy_connect_any=1

- name: "Restart haproxy service"
  systemd:
    name: haproxy
    state: started
    enabled: yes
